name: Alpha Release Docs

on:
  push:
    branches:
      - master
      - alpha

jobs:
  ui-kit-publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '(docs)')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install depedencies
        run: yarn
      - name: Build
        run: yarn workspace lubycon-ui-kit-docs build
      - name: Publish
        id: publish
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - run: echo ${{ steps.publish.outputs.release-version }}
      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.publish.outputs) }}
      # - uses: 8398a7/action-slack@v3 # 슬랙 노티피케이션
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_BOT_WEBHOOK_URL }}
      #   if: always()
        